[mypy]
python_version = 3.9
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
ignore_missing_imports = True
show_error_codes = True
namespace_packages = True
exclude = (tests|examples|docs|build|dist)/

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-examples.*]
disallow_untyped_defs = False
